name: CI
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_NODE_VERSION: 22.x

jobs:

  browserbuilds:
    name: Browser builds
    runs-on: ubuntu-latest
    steps:
      - name: Ensure line endings are consistent
        run: git config --global core.autocrlf input
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.DEFAULT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - name: Load dependency cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ secrets.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies and build
        run: yarn install --frozen-lockfile
      - name: Build browser bundles
        run: yarn run build:browser
      - name: Deploy browser builds
        if: startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/tags/')
        run: ./.github/deploy_browser.sh
        env:
          GH_TOKEN: ${{ secrets.PAT }}
